"""empty message

Revision ID: 2b986ce659a0
Revises: 9aae61812378
Create Date: 2020-06-04 14:03:35.289984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b986ce659a0'
down_revision = '9aae61812378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weibo', 'updated')
    # ### end Alembic commands ###
