"""empty message

Revision ID: 2eaca8be870d
Revises: 17cfa773a908
Create Date: 2020-06-05 15:17:17.630573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eaca8be870d'
down_revision = '17cfa773a908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo', sa.Column('n_like', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weibo', 'n_like')
    # ### end Alembic commands ###
