"""empty message

Revision ID: c44a2a52d661
Revises: 1c77f0f192c0
Create Date: 2020-06-03 11:15:00.548530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c44a2a52d661'
down_revision = '1c77f0f192c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=16), nullable=True))
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'city')
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###
